### ISSUE TITLE
Fix Path issues

### ISSUE THREAD

**Issue by MichaelGame-Dev** [bitbrain/godot-gamejam#8]
Just as a heads up you still have some filenames that start with a capital letter. 

I'm a git noob or I would submit a pull request. 

In particular thought, in the ui/components/Bootsplash.tscn scene, this is what you have:

`[ext_resource type="Script" path="res://ui/components/bootsplash.gd" id="1_3allk"]`

It should be `.../Bootsplash.gd' so either those files should be lower case or this b needs to be capitalized.

**Comment by bitbrain** [comment]
Thanks, let me fix that

**Comment by allisonverdam** [comment]
I've fix that at https://github.com/bitbrain/godot-gamejam/pull/9
